### ISSUE TITLE
chinese display in on line some words disappear

### ISSUE THREAD

**Issue by nigo81** [maaslalani/slides#120]
**Describe the bug**
if write chinese  character in one line, slides will truncated and some character disappear

**To Reproduce**
1. wite some chinese words in markdown file:
"对于没有任何编程的朋友学习Python最大的拦路虎不是语言，而是没有应用场景。笔者最开始学习Python的时候，也是看了一些网络教程，然后就没有然后了。为什么学不会？因为看教程很容易，但是看过后并不知道自己应该干些什么，没有找到实际应用场景，也就没有多少练习使用，最终就遗忘了。最后笔者是通过学习爬虫入门的。"
2. run slides, and would not show all words

**Expected behavior**
slides should truncate one line words to next line 

**Screenshots**
![image](https://user-images.githubusercontent.com/38601513/140635647-ee97261b-dfb5-42fe-904f-4a6a2fbcf3bb.png)

**Desktop (please complete the following information):**
 - OS: [ArcoLinux]
 - Browser [edge]
 - Version [0.7.2-1]

**Comment by maaslalani** [comment]
Hi, thanks for reporting this! I was able to reproduce this but I am pretty sure that `slides` is not the correct place to fix this (since we rely on https://github.com/charmbracelet/glamour for word wrapping).

In fact, even `vim` was unable to word wrap with (visual) `gq` on the text you provided which makes me think that there is something strange going on with the word wrapping in general.

As a work around, are you able to manually insert line breaks (in your `slides.md` file) to have the text fit on the screen? Like this:

![image](https://user-images.githubusercontent.com/42545625/140656418-1913fee6-a713-4a72-aa8d-11adf02b074a.png)

**Comment by nigo81** [comment]
> Hi, thanks for reporting this! I was able to reproduce this but I am pretty sure that `slides` is not the correct place to fix this (since we rely on https://github.com/charmbracelet/glamour for word wrapping).
> 
> In fact, even `vim` was unable to word wrap with (visual) `gq` on the text you provided which makes me think that there is something strange going on with the word wrapping in general.
> 
> As a work around, are you able to manually insert line breaks (in your `slides.md` file) to have the text fit on the screen? Like this:
> 
> ![image](https://user-images.githubusercontent.com/42545625/140656418-1913fee6-a713-4a72-aa8d-11adf02b074a.png)

ok, Thanks for your awesome software. `Slides` is cool.
