### ISSUE TITLE
Custom static date is interpreted wrong

### ISSUE THREAD

**Issue by h0adp0re** [maaslalani/slides#152]
**Describe the bug**
Date is interpreted strangely.

**To Reproduce**
1. Use `date: 2022-05-22`
2. See `282828-49-2828`

**Expected behavior**
Slides displays `2022-05-22`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 0.8.0

**Comment by maaslalani** [comment]
Ah this is a bug since we look if the date can be parsed in the proper format and assume it is using `2006-01-02` and use that directly as the date which is why you are seeing a weird date. As a work around if you use a different date format like (`May 22, 2022`) it should not parse as a date will simply show the string. I think as a proper solution, we should get rid of parsing `2006-01-01` dates and only use the `YYYY-MM-DD` strings and treat everything else as a static string.

**Comment by h0adp0re** [comment]
Sadly I tried all kinds of workarounds. Then found an old issue in which it was decided to use `YYYY-MM-DD` from then on, which is what I settled on.

Using `May 22, 2022` results in `May 2929, 292929`.

**Comment by maaslalani** [comment]
Oh no! This is definitely a bug for sure and I'll fix it when I have some free time. Thanks for reporting this and sorry for the inconvenience!

I really appreciate you taking the time to file these reports! & thanks for using slides 😄

**Comment by h0adp0re** [comment]
Hey no worries, man. I really enjoy slides! Thank you to you, too.

**Comment by tonytonyjan** [comment]
Hi @maaslalani! How is the progress? I really need this fix. Let us know if you need any help.

**Comment by maaslalani** [comment]
Hey! Sorry about that, here is the fix: https://github.com/maaslalani/slides/pull/170

**Comment by maaslalani** [comment]
Fix merged to `main`! 🎉

**Comment by tonytonyjan** [comment]
Thank you @maaslalani ❤️❤️❤️
