### ISSUE TITLE
Slides parsing fail on Windows

### ISSUE THREAD

**Issue by Selyss** [maaslalani/slides#231]
**Describe the bug**
Windows does not parse slide-specific text such as `---` for new slides and metadata. This issue only occurs for markdown files given in args, not for the default display with no arguments.

**To Reproduce**
1. Install slides on Windows through Go
2. Make a presentation file and cd to the directory
3. Execute `slides example.md`
4. Slides will display the characters for headings and normal markdown elements, but will not correctly build graphs, add new slides.

**Expected behavior**
Slides will display as normal, with any metadata hidden and slide divisions when encountering a `---`.

**Screenshots**
![image](https://user-images.githubusercontent.com/99344963/227749521-1e5a8b81-6073-4033-b396-b3d7238d32ec.png)

**As you can see, slides displays as normal, but doesn't recognize new slides and other program specific elements.**

---

![image](https://user-images.githubusercontent.com/99344963/227749662-8e49562a-cfb4-48c5-9459-8735226d87c0.png)

**Example of metadata issue**

---

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Terminal: Powershell (Windows Terminal App)
 - Version: Latest

**Additional context**
The program only seems to have issue with custom symbol parsing, it can display markdown as expected. Any help appreciated!

**Comment by sbh69840** [comment]
Same issue on M1 mac with wezterm
<img width="1481" alt="Screenshot 2023-04-10 at 1 11 23 PM" src="https://user-images.githubusercontent.com/23645788/230852748-33b98f40-63a1-4b3b-b7e9-80964cdac542.png">

**Comment by krakpot** [comment]
I think this issue is related to DOS "\r\n" line breaks vs Unix "\n" and slides only seem happy with the latter.

Latest `slides` installed in Windows 10 using `go`

If I open a file with DOS line breaks "---" will not be interpreted correctly:

`slides test_crlf.md`

![bild](https://github.com/maaslalani/slides/assets/1367689/126ce361-165b-4ce1-9ad9-23fb5a22dd3d)

If I explicity save this file with Unix line endings it works fine

`slides test_unix.md`

![bild](https://github.com/maaslalani/slides/assets/1367689/172998d5-1578-4f9a-a505-d3c33e1b85a8)


Example files (I hope github does no line break conversion...)
[test_crlf.md](https://github.com/maaslalani/slides/files/11488860/test_crlf.md)
[test_unix.md](https://github.com/maaslalani/slides/files/11488864/test_unix.md)

**Comment by Selyss** [comment]
> I think this issue is related to DOS "\r\n" line breaks vs Unix "\n" and slides only seem happy with the latter.
> 
> Latest `slides` installed in Windows 10 using `go`
> 
> If I open a file with DOS line breaks "---" will not be interpreted correctly:
> 
> `slides test_crlf.md`
> 
> 
> If I explicity save this file with Unix line endings it works fine
> 
> `slides test_unix.md`
> 
> ![bild](https://user-images.githubusercontent.com/1367689/238677119-172998d5-1578-4f9a-a505-d3c33e1b85a8.png)
> 
> Example files (I hope github does no line break conversion...) [test_crlf.md](https://github.com/maaslalani/slides/files/11488860/test_crlf.md) [test_unix.md](https://github.com/maaslalani/slides/files/11488864/test_unix.md)

Worked for me! What did you change about the files?

**Comment by krakpot** [comment]
The only difference is that one of the files has DOS/Windows line endings (`\n\r` instead of just `\n` as is standard in unix). I downloaded the files (as I created them when I was at work) from my comment above just to verify that github didn't do any conversion:

```bash
user$ file test_crlf.md
test_crlf.md: ASCII text, with CRLF line terminators
user$ file test_unix.md
test_unix.md: ASCII text
```

I can reproduce this also with slides v0.9.0 on macOS Ventura (installed from brew `slides--0.9.0.arm64_ventura.bottle.tar.gz`):

`slides test_crlf.md`

![bild](https://github.com/maaslalani/slides/assets/1367689/090994cc-686b-4faf-aaca-be4909816c6e)

`slides test_unix.md`

![bild](https://github.com/maaslalani/slides/assets/1367689/b84e4400-5c5e-4a6c-99e3-e5896cad753e)


If I convert `test_crlf.md` using `dos2unix` (which converts line endings to unix format) it will display correctly with multiple slides
