### ISSUE TITLE
Should evaluating code blocks require and executable md file?

### ISSUE THREAD

**Issue by vext01** [maaslalani/slides#287]
**Describe the bug**

I notice that triple tilde blocks require +x on the md file, but triple backtick blocks don't.

In the interest of security, should triple backticks require +x too?

Thanks

**Comment by maaslalani** [comment]
Hey! No, since the triple backticks are only executed if the user presses a keybind, so that would be the equivalent to the user accepting the consequences for running the command. Whereas triple tildes are run automatically (the user might not have read all of the code) so we explicitly ask for them to make it executable just as a precaution.

**Comment by vext01** [comment]
Fair enough.

I do think that #191 is a good idea though.

**Comment by maaslalani** [comment]
Yep, agreed!
