### ISSUE TITLE
Slides doesn't support scrolling large markdown files

### ISSUE THREAD

**Issue by thunder-coding** [maaslalani/slides#65]
**Describe the bug**
When a large markdown file is opened in slides, it just jumps to the last line.

**To Reproduce**
1. Install latest `slides`
2. Open a markdown file larger than ROWS

**Expected behavior**
`slides` should support scroll

**Screenshots**
No need easily reproducible

**Comment by maaslalani** [comment]
What's your use case here? I will consider adding scrolling but I feel like you might just want shorter slides.

**Comment by thunder-coding** [comment]
> What's your use case here? I will consider adding scrolling but I feel like you might just want shorter slides.

I normally use `slides` to read large `README`s, a very unique use case 😂.

**Comment by maaslalani** [comment]
Check this program out! https://github.com/charmbracelet/glow

**Comment by Babidiii** [comment]
It might be interested to add scrolling for the use case of executable blocks.
When displaying the output of a code block with Ctrl+E, it could quickly overflow the slide depending on the output.

**Comment by maaslalani** [comment]
> It might be interested to add scrolling for the use case of executable blocks.
> 
> When displaying the output of a code block with Ctrl+E, it could quickly overflow the slide depending on the output.


Do you have a specific example of when you need this? It feels to me that the output should be relatively short (at least should fit on one slide) especially if this is a code demo. I can see why we might want scrolling but I want to avoid preemptively implementing scrolling, if it encourages people to have longer outputs, which the audience won't even be able to read.

**Comment by Babidiii** [comment]
In my case i do simple slides for exploits demo, and for example when i have a slide with a simple curl over the database which return a json it could be a bit longer than the slide geometry so i can't really scroll back to the start of the content.

I agree on the fact that smaller is the slide, better will be the audience attention. 

Otherwise the workaround i used is to `tail -f` a file `output.txt` just next to the slides, but it would be prettier to add scrolling in order to avoid seeing redirection.

![image](https://user-images.githubusercontent.com/45104238/124048978-ce966d80-da17-11eb-9ccb-d0dc8d7b0deb.png)

**Comment by maaslalani** [comment]
Instead of using the file why not just `| tail -n X` (where `X` is `< terminal_rows - lines(code_block)`)

I think this will serve you much better than the file and even better than scrolling (IMO) because you won't have to scroll back to your code and it looks like the repetitive data isn't entirely useful to the presentation (a snippet would suffice, let me know if this is not the case though)

What do you think? (As a workaround, I can still probably be convinced that scrolling is a good idea, but I think for the repetitive json data the `tail -n 30` solution works better so that you can keep your code in frame and truncate the output, let me know if I'm wrong and you need the entire output displayed though)

![image](https://user-images.githubusercontent.com/42545625/124057413-69318500-d9f5-11eb-8a73-a76bc36b04a4.png)

**Comment by Babidiii** [comment]
Yes that could be a great workaround if the purpose is to show the shape of the json data without concern about the data itself.
But if you want to target a specific value inside the result you can't really predict if the field will be at the begining or the end of the result.
Moreover if the json structure is not the an array of the same "object' you will miss other key value pair which are not at the end of the result.

**Comment by pbnj** [comment]
@Babidiii - 

> But if you want to target a specific value inside the result you can't really predict if the field will be at the begining or the end of the result.

Maybe you could use `jq`'s `select()` or `match()` to target the specific value you are looking for inside the result.

For example (continuing on @maaslalani's example):

```shell
$ curl https://jsonplaceholder.typicode.com/todos | jq '.[] | select(.id == 200)'
{
  "userId": 10,
  "id": 200,
  "title": "ipsam aperiam voluptates qui",
  "completed": false
}


$ curl https://jsonplaceholder.typicode.com/todos | jq '.[] | select(.title | test("magnam"))'
{
  "userId": 3,
  "id": 57,
  "title": "pariatur et magnam ea doloribus similique voluptatem rerum quia",
  "completed": false
}
{
  "userId": 4,
  "id": 64,
  "title": "voluptas consequatur qui ut quia magnam nemo esse",
  "completed": false
}
{
  "userId": 4,
  "id": 78,
  "title": "reiciendis est magnam amet nemo iste recusandae impedit quaerat",
  "completed": false
}
{
  "userId": 8,
  "id": 155,
  "title": "voluptatem nobis consequatur et assumenda magnam",
  "completed": true
}
{
  "userId": 10,
  "id": 199,
  "title": "numquam repellendus a magnam",
  "completed": true
}
```
