### ISSUE TITLE
hiding slides in presentation mode and toggle visibility

### ISSUE THREAD

**Issue by marcotrosi** [maaslalani/slides#97]
if not already present as feature, what do you think of a hiding/skipping possibility?

let's say there are slides you don't want to show for whatever reason
- topic adaptation due to different audience
- adaptation to shorter presentation times
- slide not fully ready

```
---
hide: true
... content here ...
---
```

`hide: false` is also possible and of course the default, as I don't want to provide that for all slides.
or instead of this extra command. Maybe simply doing some trickery with the dashes. For example if the 3 dashes are 4 or 2 dashes then the slide gets hidden. Or maybe `---h` for hiding a slide. Whatever feels good to you as a solution.

And maybe a keybinding to toggle visibility of all hidden slides during presentation, which is why I didn't went with commenting out the slides, because this wouldn't be possible then, and also if you are right before a presentation and you have only few minutes left, and you want to hide some slides then the proposed ways are better.

does this sound useful?

**Comment by marcotrosi** [comment]
@maaslalani any thoughts on that? 
did I explain badly the use cases?

**Comment by maaslalani** [comment]
Hey @marcotrosi ! Sorry about the late response. I think this is a good feature but I haven't seen as much interest to make implementing worth it. I'd like to keep slides as simple as possible so that learning to use it is easy and maintaining it is easy.

Since we have live reloading something like this is already kind of possible (although would be very hacky) if you're able to have an external program modify the file and slides will reload the hidden stuff.

I'm not totally against this though. I think it could make sense to have bullet points appearing one-by-one etc... but again this is already possible by duplicating the slide ^.

I feel like hiding slides isn't a pressing feature because you could just use something like `git` to store the state and then delete the slides you want and then once you're done the presentation you can revert the changes.

I'm not totally against adding this but I haven't seen too much interest for the complexity it will add. Also, I haven't thought of a clever way to make it work.

You're explanation of the feature is great though! Thank you for such a well written issue ❤️

**Comment by maaslalani** [comment]
Personally, I think we should not do this feature for now as the costs (development, documentation, maintenance) far outweigh the benefit (IMO). I will close this issue for now but if this feature gets more requested we can revisit adding it.

Thank you for the suggestion @marcotrosi
